# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4bf341df62b0c28180051c98de53336304983405f819276a24e8c937eb6569de08621aba60d3715fa48f5da1112ecf56157f963635984352ef4eaf9f4c76c70f

test:
  secret_key_base: c544817a881b3616314b76d9d05a243708898f5089008eed6e462c134d874ab97d7f76ff98c49c95f3ab8ad80bdfba6868ba5580f302c43ac02510ae88f86793

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
